import { DEFAULT_CURRENCY } from "./expenses";
import { SUPPORTED_CURRENCIES, type SupportedCurrency } from "./currencies";

// ISO 3166-1 alpha-2 country code -> currency, limited to currencies this
// app can actually convert (SUPPORTED_CURRENCIES / what Frankfurter
// supports). Not exhaustive — covers the countries most likely to sign up,
// falling back to USD for anything unmapped rather than guessing.
const COUNTRY_CURRENCY: Record<string, SupportedCurrency> = {
  AU: "AUD",
  BR: "BRL",
  CA: "CAD",
  CH: "CHF",
  LI: "CHF",
  CN: "CNY",
  CZ: "CZK",
  DK: "DKK",
  FO: "DKK",
  GL: "DKK",
  AT: "EUR",
  BE: "EUR",
  CY: "EUR",
  EE: "EUR",
  FI: "EUR",
  FR: "EUR",
  DE: "EUR",
  GR: "EUR",
  IE: "EUR",
  IT: "EUR",
  LV: "EUR",
  LT: "EUR",
  LU: "EUR",
  MT: "EUR",
  NL: "EUR",
  PT: "EUR",
  SK: "EUR",
  SI: "EUR",
  ES: "EUR",
  AD: "EUR",
  MC: "EUR",
  SM: "EUR",
  VA: "EUR",
  GB: "GBP",
  GG: "GBP",
  IM: "GBP",
  JE: "GBP",
  HK: "HKD",
  HU: "HUF",
  ID: "IDR",
  IL: "ILS",
  IN: "INR",
  IS: "ISK",
  JP: "JPY",
  KR: "KRW",
  MX: "MXN",
  MY: "MYR",
  NO: "NOK",
  SJ: "NOK",
  NZ: "NZD",
  CK: "NZD",
  NU: "NZD",
  PH: "PHP",
  PL: "PLN",
  RO: "RON",
  SE: "SEK",
  SG: "SGD",
  TH: "THB",
  TR: "TRY",
  US: "USD",
  ZA: "ZAR",
  LS: "ZAR",
  NA: "ZAR",
  SZ: "ZAR",
};

export function currencyForCountry(countryCode: string | null | undefined): SupportedCurrency {
  if (!countryCode) return DEFAULT_CURRENCY as SupportedCurrency;
  const currency = COUNTRY_CURRENCY[countryCode.toUpperCase()];
  return currency && SUPPORTED_CURRENCIES.includes(currency) ? currency : (DEFAULT_CURRENCY as SupportedCurrency);
}
