export type DemoExpense = {
  merchant: string;
  amount: number;
  currency: string;
  date: string;
  category: string;
  tax?: number;
  note?: string;
  city?: string;
  state?: string;
  country?: string;
  items?: { name: string; price: number; quantity?: number; isWarrantyClaim?: boolean; warrantyMonths?: number }[];
};

// Sample receipts spread across March-August so every dashboard chart
// (Monthly Trend, Categories Tracked) has something to show. Shared between
// the "Get dummy data" Settings action and the one-time VPS seed script —
// one source of truth for what "the dummy data" actually is. Kept in its
// own file (no server-only imports) so client components can read
// DEMO_EXPENSES.length without pulling in the DB client.
//
// Every entry's items sum to exactly (amount - tax), like a real itemized
// receipt. Every entry also has a city/country — a fictional user based in
// Kuala Lumpur, with recurring merchants (groceries, transport, home bills)
// always resolving to the same branch/city rather than jumping around, plus
// a couple of real trips abroad (Singapore, a US business trip) that show
// up as their own pins on the location map.
export const DEMO_EXPENSES: DemoExpense[] = [
  // The 5 most recent — the exact, unedited output of a real DeepSeek
  // Quick Scan call against 5 real Malaysian hypermarket/convenience-
  // store receipts (36-41 items each), including the model's own errors
  // — this is what the scanner actually produces, not a hand-corrected
  // version of it. Merchant/item names keep DeepSeek's own ALL-CAPS
  // casing rather than being re-titled to match the rest of this file,
  // for the same reason. Dated Aug 31 - Sep 4 (display dates chosen for
  // demo positioning, not DeepSeek's own date field — see below), after
  // every other entry in this file, so they land at the top of Recent
  // Receipts for a fresh signup.
  //
  // Known, deliberately un-fixed extraction errors, left in on purpose:
  // - KK Super Mart: on ~10 lines the model read the line AMOUNT (total)
  //   as the per-unit price instead of the printed PRICE column, despite
  //   the prompt telling it not to — the same three-column layout it got
  //   right on the other 4 receipts. Correctly caught by itemsMismatch.
  // - Lotus's Express: Frozen Fries read as 2.11 instead of 11.50 — a
  //   genuine OCR digit misread, not a logic error. Small enough (~2.3%
  //   of the total) that itemsMismatch's generous threshold missed it.
  // - FamilyMart: couldn't read the printed date at all and fell back to
  //   "today," and swapped Mister Potato's price/quantity slightly.
  { merchant: "FAMILYMART", amount: 343.8, currency: "MYR", date: "2026-08-31", category: "Groceries", tax: 5.51, city: "Klang", state: "Selangor", country: "Malaysia", items: [{ name: "OYAKODON BENTO", price: 12.9 }, { name: "MASSIMO SANDWICH LOAF", price: 3.6 }, { name: "CALBEE HONEY BUTTER", price: 5.5 }, { name: "100PLUS ORIGINAL 325ML", price: 2.5 }, { name: "KITKAT MATCHA 4F", price: 5.9 }, { name: "CHICKEN KATSU CURRY", price: 13.5 }, { name: "FAMICAFE MATCHA LATTE", price: 8.9 }, { name: "FM SOJI CHEESE", price: 4.9 }, { name: "MARIGOLD HL MILK 1L", price: 8.9 }, { name: "FAMICAFE LATTE R", price: 7.2 }, { name: "SPICY KOREAN CHICKEN", price: 8.5, quantity: 3 }, { name: "FM SOJI ORIGINAL", price: 4.5 }, { name: "FM WET TISSUE 20S", price: 3.5, quantity: 3 }, { name: "FM ONIGIRI SALMON", price: 5.2 }, { name: "COCA COLA 320ML", price: 2.6, quantity: 2 }, { name: "FM ONIGIRI TUNA MAYO", price: 3.5, quantity: 3 }, { name: "TWISTIES CHICKEN 60G", price: 3.2 }, { name: "EGG TART 2PCS", price: 5, quantity: 2 }, { name: "YAKULT 5S PACK", price: 6.3 }, { name: "MENTOS MINT ROLL", price: 2.3, quantity: 2 }, { name: "REDBULL GOLD 250ML", price: 4.5 }, { name: "DURACELL AA 2S", price: 9.9, quantity: 3 }, { name: "MISTER POTATO BBQ 75G", price: 2.6, quantity: 4 }, { name: "PANADOL ACTIFAST 10S", price: 8.9 }, { name: "FM SANDWICH TUNA", price: 7.2, quantity: 3 }, { name: "POKKA GREEN TEA 500ML", price: 4.2 }, { name: "BANANA CAKE SLICE", price: 4.2 }, { name: "DETTOL WIPES 10S", price: 4.5, quantity: 2 }, { name: "FAMICAFE AMERICANO L", price: 6.5 }, { name: "MAGGI CUP CURRY", price: 3.9, quantity: 3 }, { name: "NISSIN CUP SEAFOOD", price: 5.2 }, { name: "SUPER RING 45G", price: 2.5 }, { name: "MENTAIKO PASTA", price: 11.9 }, { name: "MEIJI HELLO PANDA", price: 4.8 }, { name: "KOMBU ONIGIRI", price: 4.2, quantity: 2 }, { name: "FM MILK TEA 500ML", price: 4.9, quantity: 2 }, { name: "MILO ACTIV-GO 240ML", price: 3.2 }, { name: "FM SANDWICH EGG MAYO", price: 6.9 }, { name: "HOJICHA SOFT SERVE", price: 5.9 }, { name: "YAKITORI SKEWER 2S", price: 7.9 }] },
  { merchant: "99 SPEED MART", amount: 658.65, currency: "MYR", date: "2026-09-01", category: "Groceries", tax: 17.75, city: "Klang", state: "Selangor", country: "Malaysia", items: [{ name: "COLGATE MAXFRESH 225G", price: 12.9 }, { name: "SUNLIGHT PENCUCI 900ML", price: 7.9, quantity: 2 }, { name: "CLOROX BLEACH 1L", price: 6.5 }, { name: "DYNAMO LIQUID 2.7KG", price: 24.9 }, { name: "SOS CILI MAGGI 500G", price: 6.9, quantity: 2 }, { name: "SOS TIRAM LEE KUM KEE", price: 8.5 }, { name: "MORTEIN SPRAY 600ML", price: 15.9, quantity: 2 }, { name: "MOP REFILL", price: 11.9, quantity: 2 }, { name: "ROTI GARDENIA JUMBO", price: 3.4, quantity: 3 }, { name: "MINYAK MASAK SAJI 2KG", price: 12.5, quantity: 2 }, { name: "PEPSI 1.5L", price: 4.9 }, { name: "GULA PRAT HALUS 1KG", price: 3.1 }, { name: "AIR MINERAL SPRITZER 6", price: 11.9, quantity: 2 }, { name: "NESCAFE CLASSIC 100G", price: 15.9 }, { name: "MAGGI CUKUP RASA 308G", price: 6.4 }, { name: "HARPIC POWER PLUS", price: 8.9 }, { name: "KAYA NONA 470G", price: 8.2 }, { name: "BAWANG BESAR 1KG", price: 5.2 }, { name: "TEPUNG GANDUM CAP SAUH", price: 4.3 }, { name: "HEAD & SHOULDER 340ML", price: 21.9, quantity: 2 }, { name: "PLANTA MARGERIN 240G", price: 5.3 }, { name: "100PLUS 6X325ML", price: 12.5 }, { name: "MEE SEDAAP GORENG 5S", price: 6.2, quantity: 2 }, { name: "MILO 3IN1 18S", price: 17.9, quantity: 2 }, { name: "BAWANG PUTIH 300G", price: 3.8 }, { name: "SARDIN AYAM BRAND 425G", price: 9.9, quantity: 3 }, { name: "BERAS JATI SUPER 5KG", price: 27.9, quantity: 3 }, { name: "LIFEBUOY SABUN 4S", price: 9.9, quantity: 2 }, { name: "BAKED BEANS 425G", price: 4.5, quantity: 2 }, { name: "SUSU CAP JUNJUNG 500G", price: 8.9 }, { name: "MAGGI KARI 5X79G", price: 5.9 }, { name: "SCOTT TOWEL 2R", price: 9.5 }, { name: "BATERI ABC AAA 4S", price: 5.5 }, { name: "KICAP MASIN ADABI 340M", price: 4.2 }, { name: "BEG SAMPAN L 30S", price: 7.9 }, { name: "BAWANG MERAH 500G", price: 4.2 }, { name: "TUNA CHUNK 150G", price: 6.8 }, { name: "BOH TEH TARIK 15S", price: 11.5, quantity: 3 }, { name: "KENTANG HOLLAND 1KG", price: 6.5, quantity: 3 }, { name: "DUTCH LADY UHT 1L", price: 7.6, quantity: 2 }, { name: "KOTEX SOFT 20S", price: 8.5, quantity: 2 }] },
  { merchant: "KK SUPER MART", amount: 352.85, currency: "MYR", date: "2026-09-02", category: "Groceries", tax: 7.82, city: "Klang", state: "Selangor", country: "Malaysia", items: [{ name: "REVIVE ISOTONIC 500ML", price: 3.5 }, { name: "SPRITE 320ML", price: 2.6, quantity: 2 }, { name: "VITAGEN 5S", price: 5.9 }, { name: "MASKER MUKA 3S", price: 6.9 }, { name: "JACKER SWEATED 60G", price: 3.9 }, { name: "CORNETTO CHOC 126ML", price: 4.2 }, { name: "F&N ORANGE 325ML", price: 2.3 }, { name: "CURRY PUFF 2PCS", price: 4, quantity: 3 }, { name: "STARBUCKS DOUBLESHOT", price: 9.9, quantity: 2 }, { name: "PHONE CABLE TYPE C", price: 15.9 }, { name: "CACTUS MINERAL 1.5L", price: 2.9, quantity: 2 }, { name: "HAAGEN DAZS MINI CUP", price: 15.9 }, { name: "KACANG TUMBUK 100G", price: 3.5 }, { name: "BOSS COFFEE LATTE", price: 8.5 }, { name: "SEASONS ICE LEMON TEA", price: 2.4 }, { name: "CHEETOS FLAMIN HOT", price: 12.6, quantity: 3 }, { name: "WALLS PADDLE POP", price: 7.5, quantity: 3 }, { name: "UMBRELLA FOLDABLE", price: 59.7, quantity: 3 }, { name: "BENG BENG WAFER 5S", price: 4.9 }, { name: "MARIGOLD YOGURT 130G", price: 3.2 }, { name: "SAUSAGE BUN", price: 3.5, quantity: 2 }, { name: "PRINGLES ORIGINAL 107G", price: 17.8, quantity: 2 }, { name: "NASI LEMAK BUNGKUS", price: 13.5, quantity: 3 }, { name: "HL LOW FAT MILK 1L", price: 9.2 }, { name: "KOPIKO BROWN COFFEE", price: 3.4 }, { name: "MAGNUM ALMOND", price: 15, quantity: 2 }, { name: "TIGER BALM 10G", price: 8.5 }, { name: "MAMEE MONSTER 8S", price: 13.8, quantity: 2 }, { name: "NESCAFE ORIGINAL CAN", price: 3.6 }, { name: "MAGGI CUP ASAM LAKSA", price: 4.2 }, { name: "SAMYANG HOT CHICKEN", price: 7.9 }, { name: "HAND SANITIZER 50ML", price: 5.9 }, { name: "YEOS CHRYSANTHEMUM 250", price: 5.7, quantity: 3 }, { name: "VICKS INHALER", price: 12.9 }, { name: "PANADOL SOLUBLE 4S", price: 4.9 }, { name: "ROTI SANDWICH TUNA", price: 13, quantity: 2 }, { name: "TOBLERONE 50G", price: 8.9 }, { name: "FARM FRESH MILK 200ML", price: 7, quantity: 2 }, { name: "Discount", price: -18.16 }] },
  { merchant: "MYDIN MART", amount: 690.25, currency: "MYR", date: "2026-09-03", category: "Groceries", tax: 8.83, city: "Klang", state: "Selangor", country: "Malaysia", items: [{ name: "KANGKUNG 250G", price: 2.2 }, { name: "KOKO KRUNCH 330G", price: 13.5, quantity: 2 }, { name: "SUSU PEKAT MANIS 500G", price: 4.3, quantity: 2 }, { name: "CILI MERAH 200G", price: 5.9 }, { name: "OREN SUNKIST 4S", price: 9.5 }, { name: "IKAN KEMBUNG 500G", price: 13.9, quantity: 2 }, { name: "BERAS FAIZA SUPER 10KG", price: 42.9, quantity: 2 }, { name: "LOBAK MERAH 500G", price: 3.5 }, { name: "TISU TANDAS 20R", price: 22.9 }, { name: "TEMBIKAT MERAH 1KG", price: 3.9 }, { name: "UDANG PUTIH 300G", price: 18.9 }, { name: "PISANG BERANGAN 1KG", price: 7.9, quantity: 2 }, { name: "ASAM JAWA 200G", price: 3.8 }, { name: "BIHUN SEGERA 400G", price: 5.5, quantity: 2 }, { name: "TEMPE 200G", price: 2.5 }, { name: "KOBIS BULAT 1KG", price: 4.2, quantity: 2 }, { name: "NESTUM 450G", price: 12.9 }, { name: "HALIA 200G", price: 3.9 }, { name: "SABUN CUCI PIRING 1L", price: 8.5 }, { name: "DADA AYAM FILET 500G", price: 12.5, quantity: 3 }, { name: "KUEY TEOW SEGAR 500G", price: 3.9 }, { name: "BISKUT JACOBS 700G", price: 16.9, quantity: 2 }, { name: "PAMPERS M 52S", price: 42.9 }, { name: "QUAKER OAT 800G", price: 14.9, quantity: 3 }, { name: "GULA MELAKA 300G", price: 6.5 }, { name: "JULIES PEANUT BUTTER", price: 8.9 }, { name: "MINYAK BUAH ZAITUN 500", price: 26.9, quantity: 2 }, { name: "EPAL FUJI 4S", price: 8.9 }, { name: "MADU ASLI 500G", price: 28.9, quantity: 2 }, { name: "TIMUN 500G", price: 3.1, quantity: 3 }, { name: "SOTONG BERSIH 400G", price: 16.5 }, { name: "DAUN KARI 50G", price: 1.5, quantity: 3 }, { name: "DAGING BATANG PINANG 5", price: 24.9, quantity: 2 }, { name: "SAYUR SAWI 250G", price: 2.5, quantity: 2 }, { name: "TEPUNG BERAS 500G", price: 2.9 }, { name: "AYAM BERSIH SEJUK BEKU", price: 11.9 }] },
  { merchant: "LOTUS'S EXPRESS", amount: 813.1, currency: "MYR", date: "2026-09-04", category: "Groceries", tax: 17.11, city: "Shah Alam", state: "Selangor", country: "Malaysia", items: [{ name: "FROZEN FRIES 1KG", price: 2.11, quantity: 2 }, { name: "LAUNDRY POD 30S", price: 32.9, quantity: 2 }, { name: "APPLE JUICE 1L", price: 9.5, quantity: 2 }, { name: "KETCHUP 1KG", price: 8.9, quantity: 2 }, { name: "SPONGE SCORER 5S", price: 5.9, quantity: 2 }, { name: "MAYONNAISE 470ML", price: 10.9 }, { name: "DISHWASH LIQUID 900ML", price: 7.9 }, { name: "GREEN TEA BAG 50S", price: 9.9 }, { name: "GREEK YOGURT 500G", price: 11.9 }, { name: "FACIAL TISSUE 5S", price: 13.9 }, { name: "CHEDDAR SLICE 12S", price: 12.5 }, { name: "FROZEN MIXED VEG 500G", price: 6.9, quantity: 3 }, { name: "WET WIPES 80S", price: 8.9 }, { name: "FABRIC SOFTENER 1.5L", price: 15.9 }, { name: "GLASS CLEANER 500ML", price: 8.5, quantity: 2 }, { name: "DEODORANT ROLL ON", price: 12.9 }, { name: "SPAGHETTI 500G", price: 5.9 }, { name: "MOZZARELLA SHRED 200G", price: 14.9, quantity: 3 }, { name: "TOOTHBRUSH 3S", price: 11.9 }, { name: "AA BATTERY 4S", price: 12.9 }, { name: "PASTA SAUCE 700G", price: 12.9, quantity: 3 }, { name: "LOTUS SUGAR 1KG", price: 3.1, quantity: 2 }, { name: "LOTUS COOKING OIL 1KG", price: 8.9, quantity: 2 }, { name: "BLACK PEPPER GRINDER", price: 13.9 }, { name: "SHOWER GEL 900ML", price: 18.9, quantity: 2 }, { name: "BEEF BURGER PATTY 6S", price: 18.9 }, { name: "MUSTARD SAUCE 250G", price: 7.5, quantity: 2 }, { name: "OLIVE OIL SPRAY", price: 18.9 }, { name: "LOTUS EGG GRED A 12S", price: 9.9 }, { name: "PEANUT BUTTER 340G", price: 11.5, quantity: 3 }, { name: "CHOC MALT DRINK 1KG", price: 27.9, quantity: 3 }, { name: "LOTUS WHITE BREAD 400", price: 2.9 }, { name: "ANCHOR BUTTER 227G", price: 16.9 }, { name: "FISH FINGER 375G", price: 13.9, quantity: 2 }, { name: "FLOOR CLEANER 1.5L", price: 9.9, quantity: 3 }, { name: "TRASH BAG XL 20S", price: 9.5, quantity: 3 }, { name: "LOTUS BROWN RICE 2KG", price: 14.9 }, { name: "ORANGE JUICE 1L", price: 9.9 }, { name: "LED BULB 9W", price: 14.9 }] },

  // August
  { merchant: "Trader Joe's", amount: 42.5, currency: "USD", date: "2026-08-05", category: "Groceries", tax: 3.2, city: "Springfield", state: "IL", country: "United States", items: [{ name: "Bananas", price: 2.5 }, { name: "Almond milk", price: 4 }, { name: "Sourdough bread", price: 5.5 }, { name: "Chicken breast", price: 13.65 }, { name: "Pasta", price: 13.65 }] },
  { merchant: "Starbucks", amount: 18.9, currency: "MYR", date: "2026-08-07", category: "Food & Drink", tax: 1.1, city: "Kuala Lumpur", country: "Malaysia", note: "Morning coffee with Sarah", items: [{ name: "Caffe Latte", price: 11.03 }, { name: "Butter Croissant", price: 6.77 }] },
  { merchant: "Grab", amount: 24, currency: "MYR", date: "2026-08-09", category: "Transport", city: "Kuala Lumpur", country: "Malaysia", note: "Airport ride", items: [{ name: "Ride fare", price: 24 }] },
  { merchant: "Uniqlo", amount: 189, currency: "MYR", date: "2026-08-12", category: "Shopping", tax: 10.7, city: "Kuala Lumpur", country: "Malaysia", items: [{ name: "T-shirt", price: 56.51 }, { name: "Jeans", price: 121.79 }] },
  { merchant: "TNB", amount: 156.4, currency: "MYR", date: "2026-08-01", category: "Bills & Utilities", city: "Kuala Lumpur", country: "Malaysia", note: "Electricity bill", items: [{ name: "Electricity usage", price: 156.4 }] },
  { merchant: "Guardian Pharmacy", amount: 37.8, currency: "MYR", date: "2026-08-15", category: "Health", tax: 2.1, city: "Kuala Lumpur", country: "Malaysia", items: [{ name: "Vitamin C tablets", price: 22.9 }, { name: "Hand sanitizer", price: 12.8 }] },
  { merchant: "GSC Cinemas", amount: 32, currency: "MYR", date: "2026-08-18", category: "Entertainment", city: "Petaling Jaya", state: "Selangor", country: "Malaysia", note: "Movie night", items: [{ name: "Movie ticket", price: 13, quantity: 2 }, { name: "Popcorn combo", price: 6 }] },
  { merchant: "Din Tai Fung", amount: 96.5, currency: "SGD", date: "2026-08-20", category: "Food & Drink", tax: 6.75, city: "Singapore", country: "Singapore", note: "Business trip dinner", items: [{ name: "Xiao long bao", price: 18.9 }, { name: "Fried rice", price: 16.5 }, { name: "Iced tea", price: 4.5, quantity: 2 }, { name: "Pork dumplings", price: 22.68 }, { name: "Wontons in chili oil", price: 22.67 }] },
  { merchant: "Petronas", amount: 80, currency: "MYR", date: "2026-08-22", category: "Transport", city: "Kuala Lumpur", country: "Malaysia", note: "Fuel", items: [{ name: "RON95 fuel", price: 80 }] },
  // Desk lamp is tagged for warranty, the shelf unit isn't — the exact
  // "one receipt, mixed items" case item-level warranty tagging exists for.
  { merchant: "IKEA", amount: 245, currency: "MYR", date: "2026-08-27", category: "Home & Furniture", tax: 13.9, city: "Petaling Jaya", state: "Selangor", country: "Malaysia", note: "New desk lamp and shelves", items: [{ name: "Desk lamp", price: 83.95, isWarrantyClaim: true, warrantyMonths: 12 }, { name: "Shelf unit", price: 147.15 }] },
  { merchant: "Village Grocer", amount: 79.4, currency: "MYR", date: "2026-08-03", category: "Groceries", city: "Kuala Lumpur", country: "Malaysia", items: [{ name: "Fresh produce", price: 34.5 }, { name: "Dairy & eggs", price: 22.9 }, { name: "Snacks", price: 22 }] },
  { merchant: "OldTown White Coffee", amount: 17.5, currency: "MYR", date: "2026-08-06", category: "Food & Drink", tax: 1, city: "Kuala Lumpur", country: "Malaysia", items: [{ name: "Kopi O", price: 6.13 }, { name: "Kaya toast set", price: 10.37 }] },
  { merchant: "Grab", amount: 21, currency: "MYR", date: "2026-08-11", category: "Transport", city: "Kuala Lumpur", country: "Malaysia", items: [{ name: "Ride fare", price: 21 }] },
  { merchant: "Unifi", amount: 129, currency: "MYR", date: "2026-08-06", category: "Bills & Utilities", city: "Kuala Lumpur", country: "Malaysia", note: "Internet bill", items: [{ name: "Internet subscription", price: 129 }] },
  { merchant: "Watsons", amount: 31.6, currency: "MYR", date: "2026-08-14", category: "Health", city: "Kuala Lumpur", country: "Malaysia", items: [{ name: "Shampoo", price: 18.9 }, { name: "Vitamin C", price: 12.7 }] },
  { merchant: "Zara", amount: 178, currency: "MYR", date: "2026-08-19", category: "Shopping", tax: 10.1, city: "Kuala Lumpur", country: "Malaysia", items: [{ name: "Jacket", price: 121.68 }, { name: "Belt", price: 46.22 }] },
  { merchant: "GSC Cinemas", amount: 29, currency: "MYR", date: "2026-08-24", category: "Entertainment", city: "Petaling Jaya", state: "Selangor", country: "Malaysia", items: [{ name: "Movie ticket", price: 13, quantity: 2 }, { name: "Soda", price: 3 }] },
  { merchant: "Nando's", amount: 52.3, currency: "MYR", date: "2026-08-28", category: "Food & Drink", tax: 3, city: "Kuala Lumpur", country: "Malaysia", items: [{ name: "Half chicken", price: 36.4 }, { name: "Peri-peri chips", price: 12.9 }] },
  { merchant: "Ippudo", amount: 64.5, currency: "SGD", date: "2026-08-16", category: "Food & Drink", tax: 4.5, city: "Singapore", country: "Singapore", note: "Business trip", items: [{ name: "Akamaru ramen", price: 22.9 }, { name: "Gyoza", price: 12.9 }, { name: "Char siu rice", price: 24.2 }] },
  { merchant: "Mercato", amount: 60.9, currency: "MYR", date: "2026-08-10", category: "Groceries", tax: 3.4, city: "Kuala Lumpur", country: "Malaysia", items: [{ name: "Groceries", price: 57.5 }] },
  { merchant: "Petronas", amount: 85, currency: "MYR", date: "2026-08-25", category: "Transport", city: "Kuala Lumpur", country: "Malaysia", note: "Fuel", items: [{ name: "RON95 fuel", price: 85 }] },
  { merchant: "luckin coffee", amount: 21.2, currency: "MYR", date: "2026-08-30", category: "Food & Drink", city: "Kuala Lumpur", country: "Malaysia", items: [{ name: "Coconut latte", price: 21.2 }] },

  // July
  { merchant: "Village Grocer", amount: 88.9, currency: "MYR", date: "2026-07-05", category: "Groceries", city: "Kuala Lumpur", country: "Malaysia", items: [{ name: "Fresh produce", price: 38.9 }, { name: "Dairy & eggs", price: 25 }, { name: "Snacks", price: 25 }] },
  { merchant: "Grab", amount: 26, currency: "MYR", date: "2026-07-09", category: "Transport", city: "Kuala Lumpur", country: "Malaysia", items: [{ name: "Ride fare", price: 26 }] },
  { merchant: "TNB", amount: 141.2, currency: "MYR", date: "2026-07-01", category: "Bills & Utilities", city: "Kuala Lumpur", country: "Malaysia", note: "Electricity bill", items: [{ name: "Electricity usage", price: 141.2 }] },
  { merchant: "Guardian Pharmacy", amount: 41.6, currency: "MYR", date: "2026-07-13", category: "Health", tax: 2.3, city: "Kuala Lumpur", country: "Malaysia", items: [{ name: "Multivitamins", price: 27.3 }, { name: "Cough syrup", price: 12 }] },
  { merchant: "Trader Joe's", amount: 38.9, currency: "USD", date: "2026-07-19", category: "Groceries", tax: 2.9, city: "Springfield", state: "IL", country: "United States", note: "Business trip", items: [{ name: "Eggs", price: 5 }, { name: "Greek yogurt", price: 6.5 }, { name: "Orange juice", price: 4 }, { name: "Olive oil", price: 20.5 }] },
  { merchant: "H&M", amount: 98, currency: "MYR", date: "2026-07-27", category: "Shopping", tax: 5.6, city: "Kuala Lumpur", country: "Malaysia", items: [{ name: "T-shirt", price: 27.82, quantity: 2 }, { name: "Cap", price: 36.76 }] },
  { merchant: "AEON", amount: 66.3, currency: "MYR", date: "2026-07-03", category: "Groceries", city: "Petaling Jaya", state: "Selangor", country: "Malaysia", items: [{ name: "Groceries", price: 48.3 }, { name: "Household items", price: 18 }] },
  { merchant: "Ippudo", amount: 61.2, currency: "MYR", date: "2026-07-11", category: "Food & Drink", tax: 3.5, city: "Kuala Lumpur", country: "Malaysia", items: [{ name: "Tonkotsu ramen", price: 28.9 }, { name: "Gyoza", price: 14.9 }, { name: "Karaage chicken", price: 13.9 }] },
  { merchant: "Touch 'n Go", amount: 40, currency: "MYR", date: "2026-07-15", category: "Transport", city: "Kuala Lumpur", country: "Malaysia", note: "Toll top-up", items: [{ name: "Toll reload", price: 40 }] },
  { merchant: "TNB", amount: 144.5, currency: "MYR", date: "2026-07-02", category: "Bills & Utilities", city: "Kuala Lumpur", country: "Malaysia", note: "Electricity bill", items: [{ name: "Electricity usage", price: 144.5 }] },
  { merchant: "GSC Cinemas", amount: 30, currency: "MYR", date: "2026-07-23", category: "Entertainment", city: "Petaling Jaya", state: "Selangor", country: "Malaysia", items: [{ name: "Movie ticket", price: 13, quantity: 2 }, { name: "Soda", price: 4 }] },
  { merchant: "H&M", amount: 87, currency: "MYR", date: "2026-07-30", category: "Shopping", tax: 4.9, city: "Kuala Lumpur", country: "Malaysia", items: [{ name: "Jeans", price: 65.12 }, { name: "Socks", price: 5.66, quantity: 3 }] },

  // June
  { merchant: "Jaya Grocer", amount: 76.8, currency: "MYR", date: "2026-06-03", category: "Groceries", tax: 4.4, city: "Petaling Jaya", state: "Selangor", country: "Malaysia", items: [{ name: "Fresh produce", price: 39.41 }, { name: "Pantry items", price: 32.99 }] },
  { merchant: "Starbucks", amount: 24, currency: "MYR", date: "2026-06-11", category: "Food & Drink", tax: 1.4, city: "Kuala Lumpur", country: "Malaysia", items: [{ name: "Caffe Latte", price: 15.54 }, { name: "Blueberry muffin", price: 7.06 }] },
  { merchant: "Petronas", amount: 82, currency: "MYR", date: "2026-06-17", category: "Transport", city: "Kuala Lumpur", country: "Malaysia", note: "Fuel", items: [{ name: "RON95 fuel", price: 82 }] },
  { merchant: "GSC Cinemas", amount: 36, currency: "MYR", date: "2026-06-20", category: "Entertainment", city: "Petaling Jaya", state: "Selangor", country: "Malaysia", note: "Movie night", items: [{ name: "Movie ticket", price: 13, quantity: 2 }, { name: "Popcorn combo", price: 10 }] },
  { merchant: "Uniqlo", amount: 112, currency: "MYR", date: "2026-06-26", category: "Shopping", tax: 6.3, city: "Kuala Lumpur", country: "Malaysia", items: [{ name: "Hoodie", price: 85.81 }, { name: "Socks", price: 6.63, quantity: 3 }] },
  { merchant: "Village Grocer", amount: 95.7, currency: "MYR", date: "2026-06-06", category: "Groceries", city: "Kuala Lumpur", country: "Malaysia", items: [{ name: "Fresh produce", price: 42.7 }, { name: "Dairy & eggs", price: 28 }, { name: "Snacks", price: 25 }] },
  { merchant: "Nando's", amount: 49, currency: "MYR", date: "2026-06-13", category: "Food & Drink", tax: 2.8, city: "Kuala Lumpur", country: "Malaysia", items: [{ name: "Quarter chicken", price: 24.9 }, { name: "Peri-peri chips", price: 12.9 }, { name: "Garlic bread", price: 8.4 }] },
  { merchant: "Grab", amount: 23, currency: "MYR", date: "2026-06-19", category: "Transport", city: "Kuala Lumpur", country: "Malaysia", items: [{ name: "Ride fare", price: 23 }] },
  { merchant: "Unifi", amount: 129, currency: "MYR", date: "2026-06-06", category: "Bills & Utilities", city: "Kuala Lumpur", country: "Malaysia", note: "Internet bill", items: [{ name: "Internet subscription", price: 129 }] },
  { merchant: "GSC Cinemas", amount: 34, currency: "MYR", date: "2026-06-24", category: "Entertainment", city: "Petaling Jaya", state: "Selangor", country: "Malaysia", items: [{ name: "Movie ticket", price: 13, quantity: 2 }, { name: "Soda", price: 8 }] },
  { merchant: "Watsons", amount: 37.8, currency: "MYR", date: "2026-06-29", category: "Health", city: "Kuala Lumpur", country: "Malaysia", items: [{ name: "Shampoo", price: 22.9 }, { name: "Vitamin C", price: 14.9 }] },

  // May
  { merchant: "Village Grocer", amount: 91.3, currency: "MYR", date: "2026-05-02", category: "Groceries", city: "Kuala Lumpur", country: "Malaysia", items: [{ name: "Fresh produce", price: 39.3 }, { name: "Dairy & eggs", price: 27 }, { name: "Snacks", price: 25 }] },
  { merchant: "Grab", amount: 22.5, currency: "MYR", date: "2026-05-08", category: "Transport", city: "Kuala Lumpur", country: "Malaysia", items: [{ name: "Ride fare", price: 22.5 }] },
  { merchant: "TNB", amount: 148.7, currency: "MYR", date: "2026-05-01", category: "Bills & Utilities", city: "Kuala Lumpur", country: "Malaysia", note: "Electricity bill", items: [{ name: "Electricity usage", price: 148.7 }] },
  { merchant: "Din Tai Fung", amount: 78.2, currency: "SGD", date: "2026-05-14", category: "Food & Drink", tax: 5.5, city: "Singapore", country: "Singapore", note: "Weekend trip", items: [{ name: "Xiao long bao", price: 16.9 }, { name: "Fried rice", price: 14.5 }, { name: "Iced tea", price: 4, quantity: 2 }, { name: "Green beans", price: 16.65 }, { name: "Jasmine rice", price: 16.65 }] },
  { merchant: "Watsons", amount: 33.4, currency: "MYR", date: "2026-05-21", category: "Health", city: "Kuala Lumpur", country: "Malaysia", items: [{ name: "Sunscreen", price: 24.9 }, { name: "Face wash", price: 8.5 }] },
  { merchant: "AEON", amount: 71.2, currency: "MYR", date: "2026-05-06", category: "Groceries", city: "Petaling Jaya", state: "Selangor", country: "Malaysia", items: [{ name: "Groceries", price: 52.2 }, { name: "Household items", price: 19 }] },
  { merchant: "Starbucks", amount: 19.9, currency: "MYR", date: "2026-05-12", category: "Food & Drink", tax: 1.2, city: "Kuala Lumpur", country: "Malaysia", items: [{ name: "Caffe Latte", price: 13.63 }, { name: "Cookie", price: 5.07 }] },
  { merchant: "Petronas", amount: 78, currency: "MYR", date: "2026-05-18", category: "Transport", city: "Kuala Lumpur", country: "Malaysia", note: "Fuel", items: [{ name: "RON95 fuel", price: 78 }] },
  { merchant: "TNB", amount: 151.9, currency: "MYR", date: "2026-05-01", category: "Bills & Utilities", city: "Kuala Lumpur", country: "Malaysia", note: "Electricity bill", items: [{ name: "Electricity usage", price: 151.9 }] },
  { merchant: "Guardian Pharmacy", amount: 26.4, currency: "MYR", date: "2026-05-24", category: "Health", city: "Kuala Lumpur", country: "Malaysia", items: [{ name: "Hand sanitizer", price: 12.9 }, { name: "Vitamin C", price: 13.5 }] },
  { merchant: "Zara", amount: 210, currency: "MYR", date: "2026-05-29", category: "Shopping", tax: 11.9, city: "Kuala Lumpur", country: "Malaysia", items: [{ name: "Coat", price: 149.99 }, { name: "Scarf", price: 48.11 }] },

  // April
  { merchant: "Jaya Grocer", amount: 84.2, currency: "MYR", date: "2026-04-04", category: "Groceries", tax: 4.8, city: "Petaling Jaya", state: "Selangor", country: "Malaysia", items: [{ name: "Fresh produce", price: 41.68 }, { name: "Pantry items", price: 37.72 }] },
  { merchant: "Nando's", amount: 45.6, currency: "MYR", date: "2026-04-10", category: "Food & Drink", tax: 2.6, city: "Kuala Lumpur", country: "Malaysia", note: "Dinner with friends", items: [{ name: "Quarter chicken", price: 15.51, quantity: 2 }, { name: "Coleslaw", price: 11.98 }] },
  { merchant: "Petronas", amount: 75, currency: "MYR", date: "2026-04-16", category: "Transport", city: "Kuala Lumpur", country: "Malaysia", note: "Fuel", items: [{ name: "RON95 fuel", price: 75 }] },
  { merchant: "Guardian Pharmacy", amount: 29.9, currency: "MYR", date: "2026-04-19", category: "Health", city: "Kuala Lumpur", country: "Malaysia", items: [{ name: "Pain relief tablets", price: 15.9 }, { name: "Plasters", price: 14 }] },
  { merchant: "H&M", amount: 156, currency: "MYR", date: "2026-04-25", category: "Shopping", tax: 8.9, city: "Kuala Lumpur", country: "Malaysia", items: [{ name: "Sweater", price: 83.92 }, { name: "Jeans", price: 63.18 }] },
  { merchant: "Mercato", amount: 102.4, currency: "MYR", date: "2026-04-02", category: "Groceries", tax: 5.8, city: "Kuala Lumpur", country: "Malaysia", items: [{ name: "Groceries", price: 96.6 }] },
  { merchant: "Ippudo", amount: 58.9, currency: "MYR", date: "2026-04-08", category: "Food & Drink", tax: 3.4, city: "Kuala Lumpur", country: "Malaysia", note: "Ramen with the team", items: [{ name: "Akamaru ramen", price: 26.9 }, { name: "Gyoza", price: 12.9 }, { name: "Beer", price: 15.7 }] },
  { merchant: "Grab", amount: 19.5, currency: "MYR", date: "2026-04-13", category: "Transport", city: "Kuala Lumpur", country: "Malaysia", items: [{ name: "Ride fare", price: 19.5 }] },
  { merchant: "TM Unifi", amount: 129, currency: "MYR", date: "2026-04-06", category: "Bills & Utilities", city: "Kuala Lumpur", country: "Malaysia", note: "Internet bill", items: [{ name: "Internet subscription", price: 129 }] },
  { merchant: "GSC Cinemas", amount: 30, currency: "MYR", date: "2026-04-20", category: "Entertainment", city: "Petaling Jaya", state: "Selangor", country: "Malaysia", items: [{ name: "Movie ticket", price: 13, quantity: 2 }, { name: "Soda", price: 4 }] },
  { merchant: "Sephora", amount: 145, currency: "MYR", date: "2026-04-28", category: "Shopping", tax: 8.2, city: "Kuala Lumpur", country: "Malaysia", items: [{ name: "Moisturizer", price: 83.97 }, { name: "Lipstick", price: 52.83 }] },

  // March
  { merchant: "Village Grocer", amount: 68.4, currency: "MYR", date: "2026-03-03", category: "Groceries", city: "Kuala Lumpur", country: "Malaysia", items: [{ name: "Fresh produce", price: 32.4 }, { name: "Dairy & eggs", price: 21 }, { name: "Snacks", price: 15 }] },
  { merchant: "Starbucks", amount: 21.5, currency: "MYR", date: "2026-03-09", category: "Food & Drink", tax: 1.3, city: "Kuala Lumpur", country: "Malaysia", items: [{ name: "Caffe Latte", price: 13.62 }, { name: "Croissant", price: 6.58 }] },
  { merchant: "Grab", amount: 18, currency: "MYR", date: "2026-03-14", category: "Transport", city: "Kuala Lumpur", country: "Malaysia", items: [{ name: "Ride fare", price: 18 }] },
  { merchant: "TNB", amount: 132.1, currency: "MYR", date: "2026-03-01", category: "Bills & Utilities", city: "Kuala Lumpur", country: "Malaysia", note: "Electricity bill", items: [{ name: "Electricity usage", price: 132.1 }] },
  { merchant: "GSC Cinemas", amount: 28, currency: "MYR", date: "2026-03-22", category: "Entertainment", city: "Petaling Jaya", state: "Selangor", country: "Malaysia", items: [{ name: "Movie ticket", price: 13, quantity: 2 }, { name: "Soda", price: 2 }] },
  { merchant: "AEON", amount: 54.6, currency: "MYR", date: "2026-03-05", category: "Groceries", city: "Petaling Jaya", state: "Selangor", country: "Malaysia", items: [{ name: "Groceries", price: 40.6 }, { name: "Household items", price: 14 }] },
  { merchant: "OldTown White Coffee", amount: 16.8, currency: "MYR", date: "2026-03-11", category: "Food & Drink", tax: 1, city: "Kuala Lumpur", country: "Malaysia", items: [{ name: "Kopi O", price: 6.11 }, { name: "Kaya toast set", price: 9.69 }] },
  { merchant: "Touch 'n Go", amount: 30, currency: "MYR", date: "2026-03-16", category: "Transport", city: "Kuala Lumpur", country: "Malaysia", note: "Toll top-up", items: [{ name: "Toll reload", price: 30 }] },
  { merchant: "Unifi", amount: 129, currency: "MYR", date: "2026-03-06", category: "Bills & Utilities", city: "Kuala Lumpur", country: "Malaysia", note: "Internet bill", items: [{ name: "Internet subscription", price: 129 }] },
  { merchant: "MPH Bookstore", amount: 62.5, currency: "MYR", date: "2026-03-19", category: "Shopping", tax: 3.5, city: "Kuala Lumpur", country: "Malaysia", items: [{ name: "Novel", price: 37.67 }, { name: "Notebook", price: 21.33 }] },
  { merchant: "GNC", amount: 88, currency: "MYR", date: "2026-03-25", category: "Health", tax: 5, city: "Kuala Lumpur", country: "Malaysia", note: "Vitamins", items: [{ name: "Multivitamin bottle", price: 54.71 }, { name: "Protein bar", price: 9.43, quantity: 3 }] },
];
