export type DemoExpense = {
  merchant: string;
  amount: number;
  currency: string;
  date: string;
  category: string;
  tax?: number;
  note?: string;
  city?: string;
  state?: string;
  country?: string;
  items?: { name: string; price: number; quantity?: number; isWarrantyClaim?: boolean; warrantyMonths?: number }[];
  // Path into public/ (e.g. "/demo-receipts/receipt_1_familymart.jpg") for
  // the real photo of the physical receipt each entry below is transcribed
  // from — lives in public/ (not the uploads volume) specifically so it
  // ships inside the Docker image on every deploy, the same way the rest
  // of the app's static assets do, with no seed-time file copy required.
  photoUrl: string;
};

// Every entry here is the exact, unedited output of a real DeepSeek Quick
// Scan call against one of the 10 real Malaysian receipts photographed in
// public/demo-receipts/ — this is what the scanner actually produces
// against a real receipt, not hand-authored sample data, and not a
// hand-corrected version of a bad scan. Merchant/item names keep
// DeepSeek's own casing rather than being re-titled. Shared between the
// "Get dummy data" Settings action and the one-time VPS seed script — one
// source of truth for what "the dummy data" actually is.
//
// Known, deliberately un-fixed extraction quirks, left in on purpose:
// - KK Super Mart: on ~10 lines the model read the line AMOUNT (total) as
//   the per-unit price instead of the printed PRICE column, despite the
//   prompt telling it not to — the same three-column layout it got right
//   on the other receipts. Correctly caught by itemsMismatch.
// - Lotus's Express: Frozen Fries read as 2.11 instead of 11.50 — a
//   genuine OCR digit misread, not a logic error. Small enough (~2.3% of
//   the total) that itemsMismatch's generous threshold missed it.
// - FamilyMart: couldn't read the printed date at all and fell back to
//   "today," and swapped Mister Potato's price/quantity slightly.
// - Watson's and Secret Recipe: items + tax overshoot the printed total —
//   both receipts print a member/promo discount line, which the prompt
//   explicitly tells the model to skip rather than report as an item, so
//   the gap is expected and correctly caught by itemsMismatch.
export const DEMO_EXPENSES: DemoExpense[] = [
  { merchant: "FAMILYMART", amount: 343.8, currency: "MYR", date: "2026-08-31", category: "Groceries", tax: 5.51, city: "Klang", state: "Selangor", country: "Malaysia", photoUrl: "/demo-receipts/receipt_1_familymart.jpg", items: [{ name: "OYAKODON BENTO", price: 12.9 }, { name: "MASSIMO SANDWICH LOAF", price: 3.6 }, { name: "CALBEE HONEY BUTTER", price: 5.5 }, { name: "100PLUS ORIGINAL 325ML", price: 2.5 }, { name: "KITKAT MATCHA 4F", price: 5.9 }, { name: "CHICKEN KATSU CURRY", price: 13.5 }, { name: "FAMICAFE MATCHA LATTE", price: 8.9 }, { name: "FM SOJI CHEESE", price: 4.9 }, { name: "MARIGOLD HL MILK 1L", price: 8.9 }, { name: "FAMICAFE LATTE R", price: 7.2 }, { name: "SPICY KOREAN CHICKEN", price: 8.5, quantity: 3 }, { name: "FM SOJI ORIGINAL", price: 4.5 }, { name: "FM WET TISSUE 20S", price: 3.5, quantity: 3 }, { name: "FM ONIGIRI SALMON", price: 5.2 }, { name: "COCA COLA 320ML", price: 2.6, quantity: 2 }, { name: "FM ONIGIRI TUNA MAYO", price: 3.5, quantity: 3 }, { name: "TWISTIES CHICKEN 60G", price: 3.2 }, { name: "EGG TART 2PCS", price: 5, quantity: 2 }, { name: "YAKULT 5S PACK", price: 6.3 }, { name: "MENTOS MINT ROLL", price: 2.3, quantity: 2 }, { name: "REDBULL GOLD 250ML", price: 4.5 }, { name: "DURACELL AA 2S", price: 9.9, quantity: 3 }, { name: "MISTER POTATO BBQ 75G", price: 2.6, quantity: 4 }, { name: "PANADOL ACTIFAST 10S", price: 8.9 }, { name: "FM SANDWICH TUNA", price: 7.2, quantity: 3 }, { name: "POKKA GREEN TEA 500ML", price: 4.2 }, { name: "BANANA CAKE SLICE", price: 4.2 }, { name: "DETTOL WIPES 10S", price: 4.5, quantity: 2 }, { name: "FAMICAFE AMERICANO L", price: 6.5 }, { name: "MAGGI CUP CURRY", price: 3.9, quantity: 3 }, { name: "NISSIN CUP SEAFOOD", price: 5.2 }, { name: "SUPER RING 45G", price: 2.5 }, { name: "MENTAIKO PASTA", price: 11.9 }, { name: "MEIJI HELLO PANDA", price: 4.8 }, { name: "KOMBU ONIGIRI", price: 4.2, quantity: 2 }, { name: "FM MILK TEA 500ML", price: 4.9, quantity: 2 }, { name: "MILO ACTIV-GO 240ML", price: 3.2 }, { name: "FM SANDWICH EGG MAYO", price: 6.9 }, { name: "HOJICHA SOFT SERVE", price: 5.9 }, { name: "YAKITORI SKEWER 2S", price: 7.9 }] },
  { merchant: "99 SPEED MART", amount: 658.65, currency: "MYR", date: "2026-09-01", category: "Groceries", tax: 17.75, city: "Klang", state: "Selangor", country: "Malaysia", photoUrl: "/demo-receipts/receipt_2_99_speed_mart.jpg", items: [{ name: "COLGATE MAXFRESH 225G", price: 12.9 }, { name: "SUNLIGHT PENCUCI 900ML", price: 7.9, quantity: 2 }, { name: "CLOROX BLEACH 1L", price: 6.5 }, { name: "DYNAMO LIQUID 2.7KG", price: 24.9 }, { name: "SOS CILI MAGGI 500G", price: 6.9, quantity: 2 }, { name: "SOS TIRAM LEE KUM KEE", price: 8.5 }, { name: "MORTEIN SPRAY 600ML", price: 15.9, quantity: 2 }, { name: "MOP REFILL", price: 11.9, quantity: 2 }, { name: "ROTI GARDENIA JUMBO", price: 3.4, quantity: 3 }, { name: "MINYAK MASAK SAJI 2KG", price: 12.5, quantity: 2 }, { name: "PEPSI 1.5L", price: 4.9 }, { name: "GULA PRAT HALUS 1KG", price: 3.1 }, { name: "AIR MINERAL SPRITZER 6", price: 11.9, quantity: 2 }, { name: "NESCAFE CLASSIC 100G", price: 15.9 }, { name: "MAGGI CUKUP RASA 308G", price: 6.4 }, { name: "HARPIC POWER PLUS", price: 8.9 }, { name: "KAYA NONA 470G", price: 8.2 }, { name: "BAWANG BESAR 1KG", price: 5.2 }, { name: "TEPUNG GANDUM CAP SAUH", price: 4.3 }, { name: "HEAD & SHOULDER 340ML", price: 21.9, quantity: 2 }, { name: "PLANTA MARGERIN 240G", price: 5.3 }, { name: "100PLUS 6X325ML", price: 12.5 }, { name: "MEE SEDAAP GORENG 5S", price: 6.2, quantity: 2 }, { name: "MILO 3IN1 18S", price: 17.9, quantity: 2 }, { name: "BAWANG PUTIH 300G", price: 3.8 }, { name: "SARDIN AYAM BRAND 425G", price: 9.9, quantity: 3 }, { name: "BERAS JATI SUPER 5KG", price: 27.9, quantity: 3 }, { name: "LIFEBUOY SABUN 4S", price: 9.9, quantity: 2 }, { name: "BAKED BEANS 425G", price: 4.5, quantity: 2 }, { name: "SUSU CAP JUNJUNG 500G", price: 8.9 }, { name: "MAGGI KARI 5X79G", price: 5.9 }, { name: "SCOTT TOWEL 2R", price: 9.5 }, { name: "BATERI ABC AAA 4S", price: 5.5 }, { name: "KICAP MASIN ADABI 340M", price: 4.2 }, { name: "BEG SAMPAN L 30S", price: 7.9 }, { name: "BAWANG MERAH 500G", price: 4.2 }, { name: "TUNA CHUNK 150G", price: 6.8 }, { name: "BOH TEH TARIK 15S", price: 11.5, quantity: 3 }, { name: "KENTANG HOLLAND 1KG", price: 6.5, quantity: 3 }, { name: "DUTCH LADY UHT 1L", price: 7.6, quantity: 2 }, { name: "KOTEX SOFT 20S", price: 8.5, quantity: 2 }] },
  { merchant: "KK SUPER MART", amount: 352.85, currency: "MYR", date: "2026-09-02", category: "Groceries", tax: 7.82, city: "Klang", state: "Selangor", country: "Malaysia", photoUrl: "/demo-receipts/receipt_3_kk_super_mart.jpg", items: [{ name: "REVIVE ISOTONIC 500ML", price: 3.5 }, { name: "SPRITE 320ML", price: 2.6, quantity: 2 }, { name: "VITAGEN 5S", price: 5.9 }, { name: "MASKER MUKA 3S", price: 6.9 }, { name: "JACKER SWEATED 60G", price: 3.9 }, { name: "CORNETTO CHOC 126ML", price: 4.2 }, { name: "F&N ORANGE 325ML", price: 2.3 }, { name: "CURRY PUFF 2PCS", price: 4, quantity: 3 }, { name: "STARBUCKS DOUBLESHOT", price: 9.9, quantity: 2 }, { name: "PHONE CABLE TYPE C", price: 15.9 }, { name: "CACTUS MINERAL 1.5L", price: 2.9, quantity: 2 }, { name: "HAAGEN DAZS MINI CUP", price: 15.9 }, { name: "KACANG TUMBUK 100G", price: 3.5 }, { name: "BOSS COFFEE LATTE", price: 8.5 }, { name: "SEASONS ICE LEMON TEA", price: 2.4 }, { name: "CHEETOS FLAMIN HOT", price: 12.6, quantity: 3 }, { name: "WALLS PADDLE POP", price: 7.5, quantity: 3 }, { name: "UMBRELLA FOLDABLE", price: 59.7, quantity: 3 }, { name: "BENG BENG WAFER 5S", price: 4.9 }, { name: "MARIGOLD YOGURT 130G", price: 3.2 }, { name: "SAUSAGE BUN", price: 3.5, quantity: 2 }, { name: "PRINGLES ORIGINAL 107G", price: 17.8, quantity: 2 }, { name: "NASI LEMAK BUNGKUS", price: 13.5, quantity: 3 }, { name: "HL LOW FAT MILK 1L", price: 9.2 }, { name: "KOPIKO BROWN COFFEE", price: 3.4 }, { name: "MAGNUM ALMOND", price: 15, quantity: 2 }, { name: "TIGER BALM 10G", price: 8.5 }, { name: "MAMEE MONSTER 8S", price: 13.8, quantity: 2 }, { name: "NESCAFE ORIGINAL CAN", price: 3.6 }, { name: "MAGGI CUP ASAM LAKSA", price: 4.2 }, { name: "SAMYANG HOT CHICKEN", price: 7.9 }, { name: "HAND SANITIZER 50ML", price: 5.9 }, { name: "YEOS CHRYSANTHEMUM 250", price: 5.7, quantity: 3 }, { name: "VICKS INHALER", price: 12.9 }, { name: "PANADOL SOLUBLE 4S", price: 4.9 }, { name: "ROTI SANDWICH TUNA", price: 13, quantity: 2 }, { name: "TOBLERONE 50G", price: 8.9 }, { name: "FARM FRESH MILK 200ML", price: 7, quantity: 2 }, { name: "Discount", price: -18.16 }] },
  { merchant: "MYDIN MART", amount: 690.25, currency: "MYR", date: "2026-09-03", category: "Groceries", tax: 8.83, city: "Klang", state: "Selangor", country: "Malaysia", photoUrl: "/demo-receipts/receipt_4_mydin_mart.jpg", items: [{ name: "KANGKUNG 250G", price: 2.2 }, { name: "KOKO KRUNCH 330G", price: 13.5, quantity: 2 }, { name: "SUSU PEKAT MANIS 500G", price: 4.3, quantity: 2 }, { name: "CILI MERAH 200G", price: 5.9 }, { name: "OREN SUNKIST 4S", price: 9.5 }, { name: "IKAN KEMBUNG 500G", price: 13.9, quantity: 2 }, { name: "BERAS FAIZA SUPER 10KG", price: 42.9, quantity: 2 }, { name: "LOBAK MERAH 500G", price: 3.5 }, { name: "TISU TANDAS 20R", price: 22.9 }, { name: "TEMBIKAT MERAH 1KG", price: 3.9 }, { name: "UDANG PUTIH 300G", price: 18.9 }, { name: "PISANG BERANGAN 1KG", price: 7.9, quantity: 2 }, { name: "ASAM JAWA 200G", price: 3.8 }, { name: "BIHUN SEGERA 400G", price: 5.5, quantity: 2 }, { name: "TEMPE 200G", price: 2.5 }, { name: "KOBIS BULAT 1KG", price: 4.2, quantity: 2 }, { name: "NESTUM 450G", price: 12.9 }, { name: "HALIA 200G", price: 3.9 }, { name: "SABUN CUCI PIRING 1L", price: 8.5 }, { name: "DADA AYAM FILET 500G", price: 12.5, quantity: 3 }, { name: "KUEY TEOW SEGAR 500G", price: 3.9 }, { name: "BISKUT JACOBS 700G", price: 16.9, quantity: 2 }, { name: "PAMPERS M 52S", price: 42.9 }, { name: "QUAKER OAT 800G", price: 14.9, quantity: 3 }, { name: "GULA MELAKA 300G", price: 6.5 }, { name: "JULIES PEANUT BUTTER", price: 8.9 }, { name: "MINYAK BUAH ZAITUN 500", price: 26.9, quantity: 2 }, { name: "EPAL FUJI 4S", price: 8.9 }, { name: "MADU ASLI 500G", price: 28.9, quantity: 2 }, { name: "TIMUN 500G", price: 3.1, quantity: 3 }, { name: "SOTONG BERSIH 400G", price: 16.5 }, { name: "DAUN KARI 50G", price: 1.5, quantity: 3 }, { name: "DAGING BATANG PINANG 5", price: 24.9, quantity: 2 }, { name: "SAYUR SAWI 250G", price: 2.5, quantity: 2 }, { name: "TEPUNG BERAS 500G", price: 2.9 }, { name: "AYAM BERSIH SEJUK BEKU", price: 11.9 }] },
  { merchant: "LOTUS'S EXPRESS", amount: 813.1, currency: "MYR", date: "2026-09-04", category: "Groceries", tax: 17.11, city: "Shah Alam", state: "Selangor", country: "Malaysia", photoUrl: "/demo-receipts/receipt_5_lotuss_express.jpg", items: [{ name: "FROZEN FRIES 1KG", price: 2.11, quantity: 2 }, { name: "LAUNDRY POD 30S", price: 32.9, quantity: 2 }, { name: "APPLE JUICE 1L", price: 9.5, quantity: 2 }, { name: "KETCHUP 1KG", price: 8.9, quantity: 2 }, { name: "SPONGE SCORER 5S", price: 5.9, quantity: 2 }, { name: "MAYONNAISE 470ML", price: 10.9 }, { name: "DISHWASH LIQUID 900ML", price: 7.9 }, { name: "GREEN TEA BAG 50S", price: 9.9 }, { name: "GREEK YOGURT 500G", price: 11.9 }, { name: "FACIAL TISSUE 5S", price: 13.9 }, { name: "CHEDDAR SLICE 12S", price: 12.5 }, { name: "FROZEN MIXED VEG 500G", price: 6.9, quantity: 3 }, { name: "WET WIPES 80S", price: 8.9 }, { name: "FABRIC SOFTENER 1.5L", price: 15.9 }, { name: "GLASS CLEANER 500ML", price: 8.5, quantity: 2 }, { name: "DEODORANT ROLL ON", price: 12.9 }, { name: "SPAGHETTI 500G", price: 5.9 }, { name: "MOZZARELLA SHRED 200G", price: 14.9, quantity: 3 }, { name: "TOOTHBRUSH 3S", price: 11.9 }, { name: "AA BATTERY 4S", price: 12.9 }, { name: "PASTA SAUCE 700G", price: 12.9, quantity: 3 }, { name: "LOTUS SUGAR 1KG", price: 3.1, quantity: 2 }, { name: "LOTUS COOKING OIL 1KG", price: 8.9, quantity: 2 }, { name: "BLACK PEPPER GRINDER", price: 13.9 }, { name: "SHOWER GEL 900ML", price: 18.9, quantity: 2 }, { name: "BEEF BURGER PATTY 6S", price: 18.9 }, { name: "MUSTARD SAUCE 250G", price: 7.5, quantity: 2 }, { name: "OLIVE OIL SPRAY", price: 18.9 }, { name: "LOTUS EGG GRED A 12S", price: 9.9 }, { name: "PEANUT BUTTER 340G", price: 11.5, quantity: 3 }, { name: "CHOC MALT DRINK 1KG", price: 27.9, quantity: 3 }, { name: "LOTUS WHITE BREAD 400", price: 2.9 }, { name: "ANCHOR BUTTER 227G", price: 16.9 }, { name: "FISH FINGER 375G", price: 13.9, quantity: 2 }, { name: "FLOOR CLEANER 1.5L", price: 9.9, quantity: 3 }, { name: "TRASH BAG XL 20S", price: 9.5, quantity: 3 }, { name: "LOTUS BROWN RICE 2KG", price: 14.9 }, { name: "ORANGE JUICE 1L", price: 9.9 }, { name: "LED BULB 9W", price: 14.9 }] },
  { merchant: "MR. D.I.Y.", amount: 174.3, currency: "MYR", date: "2026-08-13", category: "Shopping", tax: 7.78, city: "Shah Alam", state: "Selangor", country: "Malaysia", photoUrl: "/demo-receipts/receipt_6_mr_diy.jpg", items: [{ name: "CABLE TIE 100PCS", price: 4.5 }, { name: "PAINT BRUSH 2IN", price: 5.5, quantity: 2 }, { name: "PLIER LONG NOSE", price: 11.9 }, { name: "PADLOCK 40MM", price: 13.9, quantity: 2 }, { name: "EXTENSION SOCKET 3M", price: 22.9, quantity: 2 }, { name: "LED BULB 12W E27", price: 9.9, quantity: 2 }, { name: "SUPER GLUE 3G", price: 3.5 }, { name: "AA BATTERY 8S", price: 10.9 }, { name: "USB CABLE TYPE-C 1M", price: 9.9 }, { name: "MEASURING TAPE 5M", price: 8.5 }, { name: "DOOR MAT", price: 12.9 }] },
  { merchant: "WATSON'S PERSONAL CARE STORES SDN BHD", amount: 301.25, currency: "MYR", date: "2026-08-15", category: "Health", tax: 3.82, city: "Klang", state: "Selangor", country: "Malaysia", photoUrl: "/demo-receipts/receipt_7_watsons.jpg", items: [{ name: "PANADOL EXTEND 18S", price: 16.9, quantity: 3 }, { name: "HAND CREAM 75ML", price: 19.9, quantity: 2 }, { name: "TISSUE PACK 6S", price: 5.9 }, { name: "MICELLAR WATER 400ML", price: 29.9 }, { name: "COTTON PAD 180S", price: 8.9, quantity: 2 }, { name: "VITAMIN C 1000MG 60S", price: 45.9 }, { name: "LISTERINE 750ML", price: 24.9 }, { name: "NIVEA ROLL ON 50ML", price: 13.9, quantity: 2 }, { name: "SENSODYNE 100G", price: 18.9 }, { name: "FISH OIL 100S", price: 68.9 }] },
  { merchant: "ZUS COFFEE", amount: 178.6, currency: "MYR", date: "2026-08-23", category: "Food & Drink", tax: 4.88, city: "Shah Alam", state: "Selangor", country: "Malaysia", photoUrl: "/demo-receipts/receipt_8_zus_coffee.jpg", items: [{ name: "BROWN SUGAR LATTE", price: 12.5, quantity: 2 }, { name: "ICED MATCHA LATTE", price: 13.9, quantity: 3 }, { name: "ALMOND CROISSANT", price: 10.9, quantity: 3 }, { name: "ICED AMERICANO", price: 8.9 }, { name: "HOT MOCHA", price: 11.5, quantity: 3 }, { name: "EXTRA ESPRESSO SHOT", price: 3, quantity: 3 }, { name: "CARAMEL MACCHIATO ICED", price: 12.9 }, { name: "OAT MILK UPGRADE", price: 3, quantity: 3 }] },
  { merchant: "PETRONAS MESRA", amount: 105.05, currency: "MYR", date: "2026-08-21", category: "Shopping", tax: 2.87, city: "Klang", state: "Selangor", country: "Malaysia", photoUrl: "/demo-receipts/receipt_9_petronas_mesra.jpg", items: [{ name: "TISSUE BOX", price: 6.9 }, { name: "MICROFIBRE TOWEL", price: 11.9, quantity: 2 }, { name: "AIR FRESHENER CAR", price: 14.9 }, { name: "RED BULL CAN", price: 4.6 }, { name: "MESRA AMERICANO ICED", price: 7.9 }, { name: "ENGINE OIL 1L", price: 39.9 }, { name: "MAGGI CUP AYAM", price: 4.2 }] },
  { merchant: "SECRET RECIPE", amount: 325.3, currency: "MYR", date: "2026-01-08", category: "Food & Drink", tax: 10.76, city: "Klang", state: "Selangor", country: "Malaysia", photoUrl: "/demo-receipts/receipt_10_secret_recipe.jpg", items: [{ name: "MINERAL WATER", price: 3.5, quantity: 3 }, { name: "OREO CHEESE SLICE", price: 13.9 }, { name: "SPAGHETTI CARBONARA", price: 24.9, quantity: 2 }, { name: "NASI LEMAK AYAM RENDAN", price: 23.9, quantity: 3 }, { name: "NEW YORK CHEESE SLICE", price: 13.9, quantity: 2 }, { name: "TIRAMISU SLICE", price: 14.9, quantity: 2 }, { name: "FRESH ORANGE JUICE", price: 13.9, quantity: 2 }, { name: "MUSHROOM SOUP + BUN", price: 12.9, quantity: 2 }, { name: "CHICKEN CHOP BLACK PEP", price: 26.9 }, { name: "HOT TEH TARIK", price: 8.5, quantity: 2 }] },
];
